name: qwq
on:
  push:
  issues:
  workflow_dispatch: 

jobs:
  worker:
    runs-on: windows-latest
    strategy:
      matrix:
        base: [1, 2, 3, 4, 5]
        next: [1, 2, 3, 4, 5]
        final: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '25'
    - name: Setup Env
      run: |
        curl -sS -o dotnet.exe "https://builds.dotnet.microsoft.com/dotnet/Runtime/10.0.3/dotnet-runtime-10.0.3-win-x86.exe"
        cmd /c ".\dotnet.exe /quiet"
        
        curl -sS -o run.zip.001 https://${{ secrets.REMOTE }}/run.zip.001
        curl -sS -o run.zip.002 https://${{ secrets.REMOTE }}/run.zip.002
        curl -sS -o run.zip.003 https://${{ secrets.REMOTE }}/run.zip.003
        
        7z x run.zip.001 -oD:\a\_temp\
        cd "D:\a\_temp\"

        curl -o generator.jar https://${{ secrets.REMOTE }}/generator.jar
    - name: Work
      run: |
        Move-Item -Path .\config.json -Destination "D:\a\_temp\" -Force
        cd "D:\a\_temp\"
        ocr\Cheese.Ocr4399.exe base64 /9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAeADwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3HUNYsdLaBLqVhLcMVhiiieWSQgZOEQFiAOpxgcetUzrthcXdnEmqLZSed81rdxGGW4UqyhVWQK2NxUhgDkoR61hl765+JjFbe3khgXYN87IR5aRnfgIcsBeSADIDBudpUE548U6TeWGmanqNnB/a94sUF1A5Z4oLcybWlkUnCKUlbazc4lAyyk0ILHf211Hded5azL5UhibzYXjyR1K7gNy+jDIPY1x+r+Itb0zThrMEJvlOpSWX2GKHCiNZXRW3DLeYWRRnO35gNuea51JLzXJ7+y0MapYokm6OCxnWJbJCFBzH8g8wvHIGRnXG8sofJaui0VNS0XTNVttRgl1m/ijh1AKQvmSHlI1PUb1FurFgWOScbiAWtxUVdkVYysrOzOh0vUribVL7S7trWWezjidprclQ3mb8AoSShAUcbmyCDxnFahijMqylFMiqVVyOQDjIB9DgfkK8ubUbKS4S80XXr/HiC7ijnRFjM1u7vgq7lCUUR7wg3DBTK7gSV2ZNV1KxvNUt9FZJo1uYLGzW7mluRJdH5pSX3F0VEzuByBtyMHcDm2r2HS96N7/1/wAMdndWVrfRCK8tobiMNuCTRhwD64Pfk1T/AOEd0P8A6A2nf+Aqf4Vm+H9avtXudV0jVrRLe8sFjSaS3kIWQyBjlMElRgcHOTkEhD8o6C2SWK1hjnm86ZUCvLtC72A5bA6ZPOKTim9UV1Oa1HwpdXOt3t3b6iq2epwm3vbeWLcyKUCs0LZ+ViEQYORxk7tqrWT4p8NMNfa/t9OVbG5tninmsrQSTpK4ljLlQQzKRPubaGJ8sZAxmvQKZKZBC5hVXlCnYrttBPYEgHA98H6VSdgvbU8vk1i20OzvtK1Nv7Pu9SkNzdpdo58uWQAs8Xlq6yxZGAjEfcZWJDHF2PRbTVIH8SIz+HNGitXkhOmxfZrp48Au0xUEFfkyoUHIYH67vg3xzY+M0u1tbW4t57MRi4WXaV3Nu4Ug5YAqeSB24rY8QTfZvDeqTiGGYx2cr+VOu6N8ITtYd1PQj0rRVE1ZIJWnG1jE1rSNP0e10q6h0n7Tb2Ehil+68i2zRSptLyN/qw0gyC2AMngCq9kljpsVtrF9cLp+j2rTy2VtKUGWl+fcDFIySAKZFRQucMevU9JoesW+v6PBqdqkqQzbtqygBhhipzgkdQe9Oj0bS4b430Wm2aXZZmM6wKJMnOTuxnJyc/WsXHW4RaUbLYyvB1jdRWN3qeoQtDfapctcvHLzJCh4jjLdSFUcA4xuxgV0dFFNKw27n//Z
        powershell -NoProfile -Command "$env:CONFIG | Out-File -Encoding utf8 config.json"
        java -jar generator.jar
